import json
import os
import argparse
import sys
from datetime import datetime

# --- PINNEO CONSTANTS ---
FLIP_RULE_PERCENT = 0.70  # Standard MAO Rule (ARV * 0.7 - Rehab)
DEFAULT_CONTINGENCY = 0.10 # 10% Rehab Contingency
CLOSING_COSTS_PERCENT = 0.03 # Estimated buying costs
QUIET = os.getenv("PINNEO_QUIET") == "1"

def log(message):
    if not QUIET:
        print(message)

# Strict ANALYSIS_SCHEMA keys
ANALYSIS_TEMPLATE = {
    "arv": None,
    "as_is_value": None,
    "comps_summary": None,
    "rent_roll_current": None,
    "rent_roll_pro_forma": None,
    "rehab_budget": None,
    "contingency_percent": DEFAULT_CONTINGENCY,
    "holding_costs": None,
    "timeline_months": None,
    "cap_rate": None,
    "cash_on_cash": None,
    "mao_flip": None,
    "mao_hold": None,
    "exit_strategy": None,
    "seller_financing_terms": None,
    "subject_to_capacity": None,
    "partner_equity_split": None,
    "status": "Draft",
    "target_offer_price": None,
    "max_offer_price": None,
    "notes": None,
    "zoning_code": None,
    "lot_size_sf": None,
    "setbacks": None,
    "overlays": None,
    "highest_best_use": None,
    "development_potential": None
}

def load_deal(slug_or_address):
    """Finds the deal folder and loads analysis.json"""
    slug = slug_or_address.lower().replace(" ", "-").replace(",", "")

    path = f"deals/active/{slug}/analysis.json"
    if not os.path.exists(path):
        available = os.listdir("deals/active")
        match = next((x for x in available if slug in x), None)
        if match:
            path = f"deals/active/{match}/analysis.json"
        else:
            print(f"❌ Deal not found: {slug}")
            sys.exit(1)

    with open(path, "r") as f:
        return json.load(f), path


def get_input(prompt, default=None, type_func=float):
    """Helper for interactive CLI inputs"""
    if default is not None:
        user_input = input(f"{prompt} [{default}]: ")
    else:
        user_input = input(f"{prompt}: ")

    if not user_input and default is not None:
        return default
    try:
        return type_func(user_input)
    except ValueError:
        print("❌ Invalid input. Please enter a number.")
        return get_input(prompt, default, type_func)


def normalize_schema(data):
    """Ensures JSON keys match ANALYSIS_SCHEMA.md exactly"""
    normalized = ANALYSIS_TEMPLATE.copy()

    # Backfill from Scout output if present
    valuation = data.get("valuation", {})
    zoning = data.get("zoning", {})

    normalized["as_is_value"] = valuation.get("assessed_value")
    normalized["zoning_code"] = zoning.get("zoning_code")
    normalized["lot_size_sf"] = zoning.get("lot_size_sf")
    normalized["development_potential"] = zoning.get("development_potential")

    return normalized


def generate_markdown_report(data, filepath):
    """Generates a human-readable Deal Memo"""
    mao = data["investment_metrics"].get("mao_flip", 0)
    arv = data["valuation"].get("arv", 0)
    rehab = data["project_costs"].get("rehab_budget", 0)

    status_icon = "🟢" if mao > 0 else "🔴"

    md_content = f"""# {status_icon} Deal Analysis: {data.get('address')}

**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Strategy:** {data["investment_metrics"].get("exit_strategy", "Review")}

---

## 💰 The Numbers (Pinneo Math)
| Metric | Value | Notes |
| :--- | :--- | :--- |
| **Buy Box (Target Offer)** | **${data["investment_metrics"].get("buy_box_target", 0):,.2f}** | *Your Strike Price* |
| **Max Allowable Offer** | ${mao:,.2f} | *70% Rule Ceiling* |
| **ARV** | ${arv:,.2f} | *Est. Resale Value* |
| **Rehab Budget** | ${rehab:,.2f} | *Est. Construction* |

## 📍 Property Specs
* **Zoning:** `{data["zoning"].get("zoning_code", "N/A")}`
* **Year Built:** {data["zoning"].get("year_built", "N/A")}
* **Lot Size:** {data["zoning"].get("lot_size_sf", 0):,} sqft
* **Building:** {data["zoning"].get("building_sqft", 0):,} sqft

## 🏗️ Development Notes
* **Development Potential:** {data["zoning"].get("development_potential", "Unknown")}
* **Scout Source:** {data.get("meta", {}).get("scout_source", "Manual")}

---
> *Generated by Pinneo OS - Phase 1 Analyzer*
"""

    report_path = filepath.replace("analysis.json", "analysis_report.md")
    with open(report_path, "w") as f:
        f.write(md_content)

    log(f"📄 Report generated: {report_path}")


def run_underwriting(slug):
    data, filepath = load_deal(slug)
    analysis = normalize_schema(data)

    log(f"\n📉 [The Underwriter] Analyzing: {data.get('address', 'Unknown Property')}")
    log("-" * 50)

    assessed = analysis.get("as_is_value") or 0
    log(f"   ℹ️  Tax Assessed Value: ${assessed:,.2f}")

    arv = get_input("💰 Input After Repair Value (ARV)", default=assessed * 1.2)
    analysis["arv"] = arv

    rehab = get_input("🔨 Input Rehab Budget", default=45000.0)
    analysis["rehab_budget"] = rehab
    analysis["contingency_percent"] = DEFAULT_CONTINGENCY

    total_rehab_cost = rehab * (1 + DEFAULT_CONTINGENCY)
    log(f"   ℹ️  Total Rehab (w/ 10% contingency): ${total_rehab_cost:,.2f}")

    max_allowable_offer_flip = (arv * FLIP_RULE_PERCENT) - total_rehab_cost
    wholesale_fee = 10000
    buy_box_price = max_allowable_offer_flip - wholesale_fee

    analysis["mao_flip"] = round(max_allowable_offer_flip, 2)
    analysis["target_offer_price"] = round(buy_box_price, 2)
    analysis["max_offer_price"] = round(max_allowable_offer_flip, 2)
    analysis["exit_strategy"] = "Flip" if max_allowable_offer_flip > 0 else "Creative_Only"

    log("-" * 50)
    log("🎯 ANALYSIS RESULT")
    log(f"   ARV:               ${arv:,.2f}")
    log(f"   Rehab:             ${total_rehab_cost:,.2f}")
    log(f"   MAO (70% Rule):    ${max_allowable_offer_flip:,.2f}  <-- MAX OFFER")
    log(f"   Wholesale Target:  ${buy_box_price:,.2f}  <-- BUY BOX")
    log("-" * 50)

    # Save back to analysis.json in strict schema
    with open(filepath, "w") as f:
        json.dump(analysis, f, indent=2)
    log(f"💾 Analysis saved to {filepath}")

    report_data = {
        "address": data.get("address"),
        "valuation": {"arv": analysis.get("arv")},
        "project_costs": {"rehab_budget": analysis.get("rehab_budget")},
        "investment_metrics": {
            "mao_flip": analysis.get("mao_flip"),
            "buy_box_target": analysis.get("target_offer_price"),
            "exit_strategy": analysis.get("exit_strategy"),
        },
        "zoning": {
            "zoning_code": data.get("zoning", {}).get("zoning_code"),
            "year_built": data.get("zoning", {}).get("year_built"),
            "lot_size_sf": data.get("zoning", {}).get("lot_size_sf"),
            "building_sqft": data.get("zoning", {}).get("building_sqft"),
            "development_potential": data.get("zoning", {}).get("development_potential"),
        },
        "meta": data.get("meta", {}),
    }
    generate_markdown_report(report_data, filepath)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("slug", help="Deal slug or address part (e.g. 'fourth-plain')")
    args = parser.parse_args()

    run_underwriting(args.slug)
